name: Run Shell Script

on:
  push:
    branches:
      - main  # Adjust this to your repository's default branch

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run the shell script
      run: |
        chmod +x sample.sh  # Ensure the script is executable
        ./sample.sh

